import {
  OFFER_URL,
  REGULAR_PRICE_NGN,
  SPECIAL_PRICE_NGN,
  WEBINAR_URL,
  type CampaignEmailTemplate,
} from "./types";

const webinar = WEBINAR_URL;
const offer = OFFER_URL;
const special = `₦${SPECIAL_PRICE_NGN.toLocaleString()}`;
const regular = `₦${REGULAR_PRICE_NGN.toLocaleString()}`;

export const AI_MONEY_CODE_EMAIL_TEMPLATES: CampaignEmailTemplate[] = [
  {
    day: 1,
    subject: "I need to ask you something uncomfortable",
    preview: "You already use software every day. The question is whether you stay only a user.",
    ctaLabel: "Watch the free training",
    ctaUrl: webinar,
    body: [
      "I am writing to you as someone who already bought LeadThur, not as a stranger.",
      "That matters, because this is not another random promo. It is about a skill most people never seriously consider until the cost of ignoring it becomes obvious.",
      "You already live inside software. Banking apps. Delivery apps. WhatsApp. Dashboards. Booking tools. Spreadsheets pretending to be systems. Every day, you pay with attention, money, or both for tools other people built.",
      "Here is the uncomfortable question: what if one of the real advantages in the next few years is not just using more tools, but knowing how to build useful ones?",
      "I am hosting a free training called How To Build Software With AI And Get Paid For It. It is sixty minutes. Practical. No fluff about becoming a genius overnight.",
      "Inside it, I walk through how to turn a real problem into something you can actually build, how AI helps from the first step, what to do when things break, how to put work online for real people, and how money can come from clients or from owning what you build.",
      "You do not need to buy anything today. You need to understand what this skill actually looks like before your personal price window for the full program closes.",
      "If you have ever thought, \"I have ideas, but I am not technical,\" this is the cleanest place to start.",
    ],
  },
  {
    day: 2,
    subject: "Users rent. Owners decide.",
    preview: "There is a quiet difference between depending on software and being able to create it.",
    ctaLabel: "See how ownership changes the game",
    ctaUrl: webinar,
    body: [
      "Most people only ever experience the user side of technology.",
      "You open an app. You fill a form. You wait for an update. You pay a subscription. You hope the company does not change pricing, remove a feature, or shut down the exact workflow you depend on.",
      "Owners sit on a different side of that relationship. They decide what gets built. They decide how the problem is solved. They can charge for access. They can improve the product from real feedback. They are not stuck waiting for someone else's roadmap.",
      "I am not saying every software founder becomes wealthy. That would be dishonest. I am saying many of the world's largest companies derive enormous value from owning technology products and platforms, and that owning or building useful technology can create opportunities traditional employment alone may not provide.",
      "LeadThur exists because a painful business problem needed a better process. In the first three months it reached 782 users and an estimated ₦15,120,000 in revenue. That did not happen because of hype. It happened because the product solved something people were already struggling with.",
      "You do not have to build the next Facebook. You need to understand how ownership works, even at a small and practical level.",
      "In the free training, I show the difference between consuming tools and creating tools that people will pay for. Watch it while you still have time to decide calmly about the full program at your current special price.",
    ],
  },
  {
    day: 3,
    subject: "Why software used to feel impossible for people like us",
    preview: "The old barrier was not ambition. It was cost, access, and technical gatekeeping.",
    ctaLabel: "Watch what has changed",
    ctaUrl: webinar,
    body: [
      "For a long time, software building had a brutal entry fee.",
      "If you were not a developer, you needed one. If you needed one, you needed money. If you needed money, you needed enough conviction to spend before you even knew whether the idea worked. That is how good ideas die quietly.",
      "I have watched people get quotes that sound like a house deposit. One conversation. One estimate. Idea closed.",
      "That barrier was real. It still exists in some forms. AI does not erase complexity, deadlines, or the need to think clearly. What it changes is the starting point. You no longer need a full engineering budget just to test whether a simple workflow tool is worth building.",
      "The free training is honest about this. It does not say magic happens when you type one prompt. It shows a process: define the problem, shape a buildable version, use AI with direction, recover when something breaks, and ship something people can actually use.",
      "If you have been waiting for \"the right technical partner,\" ask yourself whether that wait has produced anything concrete in the last twelve months.",
      "Start with the free webinar. Understand the new path before your personal special-price window for the complete program expires.",
    ],
  },
  {
    day: 4,
    subject: "LeadThur is closing down",
    preview: "Not the company. Read carefully.",
    ctaLabel: "Watch the free webinar",
    ctaUrl: webinar,
    body: [
      "Let me clear the headline immediately: LeadThur is not shutting down.",
      "What needs to close down is the quiet belief that only \"tech people\" can create software businesses, and that everyone else must permanently rent other people's tools.",
      "If LeadThur disappeared tomorrow, what would you still own? Your contacts? Your process knowledge? Your ability to rebuild a system that finds and organizes business opportunities? Or would you mostly own a login?",
      "That question is not meant to scare you. It is meant to wake you up. Dependency on tools you cannot create or replace is fragile. Learning how to build useful software gives you another option.",
      "LeadThur's early numbers matter here for one reason only: they show what can happen when a real problem meets a working product. 782 users. An estimated ₦15,120,000 in the first three months. The lesson is not \"copy LeadThur.\" The lesson is that ownership compounds in a way effort alone often does not.",
      "In the free training, I break down how to move from idea to something shippable with AI in the loop, without pretending you will never hit errors or need judgment.",
      "Watch it. Then decide, before your personal price window ends, whether this skill is worth owning for yourself.",
    ],
  },
  {
    day: 5,
    subject: "Your best software idea is probably boring",
    preview: "That is usually a compliment.",
    ctaLabel: "Learn the idea framework",
    ctaUrl: webinar,
    body: [
      "People wait for a \"big idea\" the way some people wait for a perfect business plan.",
      "Meanwhile, the money often sits inside boring, repeated frustration. School admins tracking fees in five places. Shop owners who lose customer follow-up. Agencies drowning in manual reporting. Logistics teams copying the same details into WhatsApp every hour.",
      "You do not need to invent a new category. You need a problem that already exists, hurts often enough, and can be reduced into a clear workflow.",
      "Your notes app, your chats, your workplace complaints, your own daily bottlenecks — that is usually where the idea is hiding. Not in inspiration. In irritation.",
      "In the free training, I show how to turn those daily complaints into a buildable software opportunity. Not a fantasy pitch deck. A practical shape: who feels the pain, what they do today, what a simpler version could look like, and how to start building without waiting for perfection.",
      "If you think you \"do not have an idea,\" you are probably overlooking the ones that feel too ordinary to respect.",
      "Watch the webinar while you still have room inside your personal special-price window to decide about the deeper program.",
    ],
  },
  {
    day: 6,
    subject: "Businesses are already paying for this kind of help",
    preview: "You do not need a viral product to start earning.",
    ctaLabel: "See the client path",
    ctaUrl: webinar,
    body: [
      "Here is a path many people skip because it sounds less glamorous than launching an app for millions of strangers.",
      "Build for one business with a real problem. Get paid. Deliver. Learn. Then decide whether to productize later.",
      "Shade earned ₦650,000 from one ecommerce website project. That is one client result, not a guarantee for you. What it proves is simpler: businesses pay for outcomes. They do not pay for certificates. They pay when something works and removes friction.",
      "Every city has shops, clinics, schools, agencies, landlords, and operators stuck in messy processes. Some of those processes can be improved with software. Not all. Enough.",
      "The free training covers how to make money by building for clients, how to think about packaging the work, and how to avoid the trap of building endlessly with no commercial path.",
      "If you want income before you own a product, client work is often the more grounded entry.",
      "Watch the webinar. Understand this path clearly before your personal ₦49,999 window for the full program moves closer to closing.",
    ],
  },
  {
    day: 7,
    subject: "There is a difference between a fee and an asset",
    preview: "Client money pays bills. Ownership can change the shape of your income.",
    ctaLabel: "Compare both paths in the training",
    ctaUrl: webinar,
    body: [
      "Client work is powerful. Ownership is different.",
      "When you build for a client, you get paid for delivery. That can be excellent. It can fund your life. It can teach you faster than theory. It can also reset to zero when the project ends, unless you structure retainers or follow-on work.",
      "When you own a useful product, the relationship changes. People can keep paying for access. Improvements can benefit every user, not one. Distribution can scale beyond the hours in your day. Still hard. Still uncertain. But structurally different.",
      "I am not telling you to abandon clients and chase a fantasy SaaS empire. I am saying you should understand both roads.",
      "LeadThur is an ownership story. One client project that generated ₦10,000,000 is a problem-solving story. Shade and Chinedu are delivery stories. Together they show that software skill can create value in more than one shape.",
      "In the free training, I explain when to choose client work, when ownership makes sense, and how AI changes the cost of testing either path.",
      "Learn both options now, while you still have a personal special-price decision window on the complete program.",
    ],
  },
  {
    day: 8,
    subject: "What if your app breaks on day three?",
    preview: "This fear stops more people than \"I cannot code.\"",
    ctaLabel: "See what to do when things fail",
    ctaUrl: webinar,
    body: [
      "Apps break. Buttons stop responding. Forms fail. Payments misbehave. Deployments spit errors. If that sentence makes you want to close this email, stay with me.",
      "The fear is not silly. The fear is incomplete. Breaking is normal. Quitting at the first break is optional.",
      "What separates people who finish from people who freeze is not talent. It is a recovery process: notice what failed, isolate the cause, ask better questions, test the fix, and move again.",
      "AI can help here, but only if you know how to give it context. Paste the error. Explain what you expected. Show the last working state. Iterate. That is a skill, not a personality trait.",
      "The free training includes what to do when something breaks, because pretending everything works first time is how courses create false confidence.",
      "If your hesitation is \"I will get stuck and look foolish,\" that is exactly the kind of hesitation this training is built to reduce.",
      "Watch it before your personal price window ends. Understanding recovery is part of deciding whether the full program is worth it.",
    ],
  },
  {
    day: 9,
    subject: "\"I am not technical\" is not the end of the conversation",
    preview: "It is usually the beginning of an honest one.",
    ctaLabel: "See how non-coders actually start",
    ctaUrl: webinar,
    body: [
      "If you have told yourself you are not technical, I believe you mean something specific.",
      "You mean you do not write code fluently. You mean documentation looks foreign. You mean developer conversations make you feel behind. That is valid. Pretending otherwise helps nobody.",
      "What is not valid is treating that as a permanent wall in 2026.",
      "The point of this training is not to turn you into a traditional engineer overnight. The point is to teach you how to direct AI through real build steps with clarity, while you remain the operator who decides what matters.",
      "You still need judgment. You still need to describe the problem. You still need to check whether the output makes sense. AI accelerates execution. It does not replace responsibility.",
      "I designed How To Build Software With AI And Get Paid For It for capable people who are non-technical, not for people hunting guaranteed money with zero effort.",
      "If coding fear has delayed you for years, watch the free webinar and let me show the workflow without the performance theater.",
      "Do it while your personal special-price window for the full program is still open.",
    ],
  },
  {
    day: 10,
    subject: "\"I don't have an idea\" usually means this",
    preview: "You are searching in the wrong place.",
    ctaLabel: "Find problems worth solving",
    ctaUrl: webinar,
    body: [
      "When people say they have no idea, they often mean they have no idea that feels impressive enough to announce.",
      "That standard is expensive. It keeps you waiting while ordinary problems keep paying other people.",
      "Look for repetition. Look for complaints. Look for workarounds. Look for places where money, time, or trust leaks every week. A school tracking attendance on paper. A retailer who cannot see which products move. A service business that forgets follow-ups.",
      "Then ask a narrower question: what is the smallest useful version of a tool that would reduce that pain?",
      "In the free training, I show practical ways to find software ideas from your environment, then convert them into a blueprint you can actually build.",
      "You are not hunting inspiration. You are hunting friction.",
      "Watch the webinar. Bring a notebook. Your \"no idea\" may only need better questions before your personal deadline forces a more expensive decision on the full program.",
    ],
  },
  {
    day: 11,
    subject: "Proof without fairy tales",
    preview: "Here is what I can stand behind, and what I will not invent.",
    ctaLabel: "Watch the free training",
    ctaUrl: webinar,
    body: [
      "I would rather under-claim than sell you a fantasy.",
      "LeadThur: 782 users and an estimated ₦15,120,000 in revenue in the first three months. That is a real product solving a real acquisition problem.",
      "One client project generated ₦10,000,000 because a serious operational pain got solved. Shade earned ₦650,000 from one ecommerce website client. Chinedu earned ₦480,000 from one website project, and the same client returned asking for a second one. That second request matters. Repeat demand is a signal.",
      "Separately, PromptEarn has given out 20+ cars and processed ₦800M+ in transactions. That supports operator credibility only. Keep the distinction clear: it is not evidence that this AI software-building curriculum produced PromptEarn.",
      "None of these numbers are a promise about your bank account next month. They are evidence that solving real problems with software can create meaningful commercial outcomes when execution is present.",
      "The free training exists so you can see the process before you decide on the full program.",
      "Watch it with a clear head, and decide before your personal ₦49,999 window expires.",
    ],
  },
  {
    day: 12,
    subject: "Boring software can be very expensive for the people who need it",
    preview: "Pain pays. Novelty often does not.",
    ctaLabel: "See why ordinary problems win",
    ctaUrl: webinar,
    body: [
      "If your idea sounds exciting at a dinner table, that does not mean a customer will pay for it.",
      "If your idea sounds dull but removes a costly weekly headache, you may be closer to money than you think.",
      "Booking chaos. Lead follow-up. Inventory blind spots. Staff reporting. Payment reconciliation. Customer records scattered across phones. These are not glamorous. They are expensive.",
      "Businesses do not buy software because it is clever. They buy it because the current way of working is leaking money, time, or trust.",
      "That is why boring ideas can outperform flashy ones. Flashy ideas attract compliments. Painful processes attract budgets.",
      "In the free training, I show how to evaluate ideas through pain, frequency, and willingness to pay, not through how impressive the pitch sounds.",
      "You do not need the next billion-dollar category. You need one painful process you can improve for a specific group of people who already feel the cost.",
      "Watch the webinar before your personal special-price deadline makes the full program more expensive to enter.",
    ],
  },
  {
    day: 13,
    subject: "From complaint to customer: what the journey actually looks like",
    preview: "A practical walkthrough, not a motivational poster.",
    ctaLabel: "Walk through the process with me",
    ctaUrl: webinar,
    body: [
      "Let me make this concrete.",
      "Someone complains that they keep losing track of customers who asked for a quote. Today they use WhatsApp, memory, and luck. Leads go cold. Revenue leaks.",
      "A better shape appears: a simple tool that captures the lead, stores status, reminds follow-up, and shows what is pending. Not a giant CRM. A focused workflow.",
      "Then comes the build: define screens, decide what data matters, use AI to help implement, test the painful path, fix what breaks, put it online, and either sell it to similar businesses or use it as a client deliverable.",
      "Notice what did not happen in that story. There was no celebrity launch. No viral moment. No need to invent a brand-new industry. There was a complaint, a shape, a build, and a commercial path.",
      "That is the journey. Problem. Shape. Build. Recover. Ship. Monetize.",
      "The free training is built around that sequence. Not random tool tutorials. Not empty inspiration.",
      "If you want to see how this works end to end, watch the webinar while you still have a personal decision window at the current special price for the complete program.",
    ],
  },
  {
    day: 14,
    subject: "The quiet cost of staying only a consumer",
    preview: "No fake fear. Just opportunity cost.",
    ctaLabel: "Watch before you postpone again",
    ctaUrl: webinar,
    body: [
      "Waiting does not always feel like a decision. It feels like \"later.\"",
      "But later has a shape. Another year of using tools without knowing how to create them. Another year of depending on expensive quotes for ideas you never test. Another year of watching other people package skills you could have started learning.",
      "I am not saying you will miss a once-in-a-lifetime lottery ticket. I am saying skills compound. Delay also compounds.",
      "You already invested in LeadThur because you understand leverage in business discovery. This training is about leverage in building. Different skill. Same principle: stop depending only on systems you cannot shape.",
      "The free webinar gives you enough clarity to decide whether the full program belongs in your next season.",
      "You do not have to buy today. You should understand what you are deciding about before your personal deadline passes.",
      "Watch the training. Make an informed choice while your special-price window is still open.",
    ],
  },
  {
    day: 15,
    subject: "If you watch only one thing from me, make it this",
    preview: "A clear summary of what the free training actually covers.",
    ctaLabel: "Attend the free webinar",
    ctaUrl: webinar,
    body: [
      "Before I start talking about the full program in more detail, I want you on the free training.",
      "In sixty minutes you will see: how to turn an idea into something buildable, how to use AI from the first step, what to do when something breaks, how to put work online for real people, how client money can work, how ownership can work, how to find ideas, and how to get customers for what you build.",
      "That is not a teaser list. That is the agenda.",
      "If you skip the webinar, you will be deciding about the paid program with incomplete information. That is a bad way to spend money and a worse way to miss an opportunity.",
      "I would rather you watch the training and decide before your personal price window ends than wake up after your deadline wishing you had looked into it properly.",
      "The program itself is not disappearing. Your current special-price window is what expires.",
      "Register and watch. Then decide with your eyes open.",
    ],
  },
  {
    day: 16,
    subject: "The full program is available now",
    preview: `How To Build Software With AI And Get Paid For It — currently ${special}.`,
    ctaLabel: "Review the full program",
    ctaUrl: offer,
    body: [
      "The free training opens the door. The paid program is for people who want the complete implementation path.",
      "How To Build Software With AI And Get Paid For It is available now. You can join now. You can start learning now. This is not a waitlist. This is not \"coming soon.\"",
      `Right now, you qualify for the special price of ${special}. After your personal deadline, the program remains available at ${regular}. Only the special price expires.`,
      "The program is built as a sequence: set up properly, learn to direct AI, turn ideas into blueprints, prompt with structure, make the product usable, make it function, make it remember data, recover when it breaks, put it on the internet, and prepare for app stores where relevant.",
      "Stated training value is ₦450,000. That figure is context for the depth of the curriculum, not a claim about what you will earn.",
      "If the webinar made the opportunity feel real, this is the guided version for people who want to execute with structure instead of piecing fragments together.",
      "Review everything included and decide before your personal special-price window closes.",
    ],
  },
  {
    day: 17,
    subject: "What the first modules actually teach you to do",
    preview: "Setup, AI direction, and turning ideas into blueprints.",
    ctaLabel: "See the curriculum details",
    ctaUrl: offer,
    body: [
      "Let me make the early modules practical, not abstract.",
      "The Zero-To-Builder Setup is about getting your environment ready so you are not fighting tools before you even start. Messy setup creates fake failure.",
      "Teaching AI To Build For You is about direction. Vague prompts create vague output. Clear goals, constraints, and iteration create usable progress.",
      "The Idea-To-Blueprint System is where most people should spend more time than they want to. A weak idea dressed in beautiful screens is still a weak idea. A strong problem shaped into a blueprint can survive imperfect first builds.",
      "These modules exist because beginners usually fail in the same places: they start without structure, prompt randomly, and build before they understand the job the software should do.",
      "If you want that structure instead of improvising alone, the program is available now at your current special price.",
      `After your personal deadline, entry becomes ${regular}. The training remains available either way.`,
    ],
  },
  {
    day: 18,
    subject: "From screens that look okay to software that actually works",
    preview: "Design, functionality, memory, safety, deployment, app stores.",
    ctaLabel: "See what the later modules cover",
    ctaUrl: offer,
    body: [
      "A lot of AI demos stop at \"it looks interesting.\"",
      "Real software has to do more. Making Your App Look Good is not vanity. Confused users do not convert, do not return, and do not recommend.",
      "Making Your App Actually Work is where features stop being screenshots and start behaving. Making Your App Remember Things is where data, accounts, and continuity enter the picture. Without memory, most products are toys.",
      "Your Safety Net exists because shipping without recovery skills is how people abandon projects. Putting Your App On The Internet is the line between private experiments and real access. Getting Into The App Stores matters when distribution requires it.",
      "That is the arc of the ten modules. Not random topics. A path from zero to public usefulness.",
      "If you have been collecting AI tips without a complete path, this is the difference.",
      "Review the program while your personal special-price window is still open.",
    ],
  },
  {
    day: 19,
    subject: "Random prompting is not a method",
    preview: "The Prompt Playbook exists for a reason.",
    ctaLabel: "See the Prompt Playbook in context",
    ctaUrl: offer,
    body: [
      "Typing \"build me an app\" into a chat window is not a business process.",
      "AI is powerful and also obedient in the wrong direction. If your instructions are vague, it will confidently produce something that looks finished and fails under real use.",
      "The Prompt Playbook inside the program is about workflows: how to brief, how to constrain, how to revise, how to ask for alternatives, how to debug with context, and how to keep yourself in the driver's seat.",
      "This matters because people waste weeks \"using AI\" without building anything commercially useful. The missing piece is usually method, not access to tools.",
      "A method turns AI from a novelty into an assistant you can manage. Without a method, you get screenshots, false confidence, and abandoned projects.",
      "If your current approach is screenshots of prompts and hope, you need a better operating system for the work.",
      "The full program gives you that structure, and it is available now.",
      `Your current entry price is ${special} until your personal deadline. After that, ${regular}.`,
    ],
  },
  {
    day: 20,
    subject: "If users get confused, your software has a problem",
    preview: "Working code with a confusing interface still fails commercially.",
    ctaLabel: "Review the program",
    ctaUrl: offer,
    body: [
      "I have seen tools that technically \"work\" and still die.",
      "People open them, hesitate, mis-click, cannot find the next step, and leave. The builder says, \"But the feature exists.\" The market answers with silence.",
      "Making Your App Look Good is about usability and clarity. Labels. Flow. Hierarchy. Reducing cognitive load. Helping a busy person complete a job without a tutorial sermon.",
      "This is especially important if you plan to sell to businesses. Owners are impatient. Staff are busy. Nobody wants to learn your cleverness. They want the task done.",
      "Design is not decoration here. Design is commercial friction control. A clean path through a tool can matter as much as the feature list behind it.",
      "If customers cannot complete the job quickly, they will blame the software even when the logic underneath is sound.",
      "If you want to learn how to build software people can actually use, not just admire in a demo, the program is available now.",
      "Decide before your personal special-price window expires.",
    ],
  },
  {
    day: 21,
    subject: "Software becomes useful when it remembers and behaves",
    preview: "Data, functionality, and real user needs — not demos.",
    ctaLabel: "See how useful apps are built",
    ctaUrl: offer,
    body: [
      "A demo can impress for five minutes. Useful software has to survive Tuesday morning.",
      "That means functionality under real conditions. It means remembering users, records, statuses, and history. It means handling the boring cases, not only the happy path.",
      "Making Your App Actually Work and Making Your App Remember Things exist because this is where many AI-assisted builds collapse. People get a pretty shell, then discover they never designed the data or the logic.",
      "If you want client money or product revenue, usefulness beats novelty. A tool that stores the right information and behaves predictably will outperform a flashy prototype every week of the year.",
      "The program walks you through building that usefulness with AI support and operator discipline.",
      "It is available now at your current special price.",
      "After your personal deadline, the same program remains available at the regular price. The only thing that changes is what you pay to enter.",
    ],
  },
  {
    day: 22,
    subject: "If only you can open it, it is not in the market yet",
    preview: "Deployment is the line between private experiments and real software.",
    ctaLabel: "See the deployment path",
    ctaUrl: offer,
    body: [
      "There is a moment every builder hits: the thing works on their machine, and nobody else can use it.",
      "That is not a product yet. That is a local experiment.",
      "Putting Your App On The Internet is where real feedback begins. Real users. Real complaints. Real improvements. Real opportunities to charge.",
      "Getting Into The App Stores matters when your distribution path requires it. Not every product needs that on day one. Every serious builder needs to understand the difference between private and public.",
      "Many AI courses stop before this point. That is why people finish lessons and still have nothing customers can touch. They learned prompts. They never shipped.",
      "Shipping is where learning becomes commercial. Until then, you only have a private experiment sitting on your laptop.",
      "If you want the complete path, including deployment, the program is available now.",
      "Review it before your personal ₦49,999 window closes.",
    ],
  },
  {
    day: 23,
    subject: "The client money path, without fantasy income promises",
    preview: "Supported examples. Honest limits. Practical packaging.",
    ctaLabel: "See if the client path fits you",
    ctaUrl: offer,
    body: [
      "If you want income while you learn, client work can be the most grounded path.",
      "Shade's ₦650,000 ecommerce project and Chinedu's ₦480,000 website project, followed by a return request for a second site, are examples of paid delivery. A separate client project that generated ₦10,000,000 shows what solving serious operational pain can be worth. These are results that happened. They are not your guaranteed outcome.",
      "The Get-Paid Guide and related bonuses in the program exist to help you think about packaging, selling, and delivering software-related value without pretending every beginner lands a seven-figure deal on week one.",
      "Your job is still to find real demand, communicate clearly, deliver, and improve.",
      "If that path appeals to you, the program gives you both the building skill and the commercial framing.",
      "It is available now.",
      `Enter at ${special} before your personal deadline, or later at ${regular}. The training stays available either way.`,
    ],
  },
  {
    day: 24,
    subject: "Owning a useful product is a different kind of leverage",
    preview: "An asset path, not a guaranteed fortune.",
    ctaLabel: "Explore the ownership path",
    ctaUrl: offer,
    body: [
      "Ownership is attractive for a reason. It can create recurring value. It can scale beyond one client's project timeline. It can become an asset you improve over time.",
      "It can also fail. Products fail when the problem is weak, distribution is ignored, or the builder never ships.",
      "LeadThur's early traction is useful here as an ownership example: a product solving a painful workflow, reaching 782 users and an estimated ₦15,120,000 in the first three months. That is what focused problem-solving can look like. It is not a script you copy line by line.",
      "The Software Marketplace Guide and Idea Vault bonuses support this path by helping you think about demand and distribution, not only code.",
      "If you want ownership, start with usefulness and distribution discipline, not with daydreams about passive income.",
      "The full program is available now at your special price until your personal deadline.",
      "After that deadline, it remains available at ₦100,000.",
    ],
  },
  {
    day: 25,
    subject: "\"I don't have time\" usually hides a priority problem",
    preview: "Honest talk about busy people and real skill acquisition.",
    ctaLabel: "See how the program is structured",
    ctaUrl: offer,
    body: [
      "If your calendar is full, I believe you. Life does not pause for a new skill.",
      "The question is not whether you have empty hours. Almost nobody does. The question is whether this skill is important enough to claim a few protected hours a week.",
      "The program is modular on purpose. You can move sequentially without needing a sabbatical. Lifetime access and free updates exist so you are not racing an artificial content expiry clock.",
      "What does not work is waiting for a mythical free month. That month rarely arrives. Skills are usually built in imperfect weeks by people who protect a little time anyway.",
      "If you can carve time for scrolling, meetings, and firefighting other people's systems, you can carve time to learn how to build systems of your own.",
      "Review the program and decide whether the trade is worth it before your personal special-price window ends.",
      "Busy is real. Permanent postponement is a choice.",
    ],
  },
  {
    day: 26,
    subject: "Yes, AI makes mistakes. That is why the method matters.",
    preview: "Inspection, testing, debugging, and iteration are part of the job.",
    ctaLabel: "See the Safety Net approach",
    ctaUrl: offer,
    body: [
      "If your objection is that AI hallucinates, invents, or breaks things, you are paying attention.",
      "That is exactly why \"just use AI\" is incomplete advice. You need to inspect output. You need to test. You need to debug. You need to iterate. You need a safety process.",
      "Your Safety Net module exists for this reason. Professionals are not people who never encounter bugs. Professionals recover faster and ship with fewer blind spots.",
      "AI without judgment creates confident garbage. AI with operator discipline creates speed. The difference is not the model. The difference is how you use it.",
      "Treat inspection and testing as part of building, not as an optional cleanup step after the excitement fades.",
      "If this fear has kept you from starting, it should instead keep you from starting without a method.",
      "The program teaches that method, and it is available now.",
      "Decide before your personal deadline turns the current special price into the regular price.",
    ],
  },
  {
    day: 27,
    subject: `Is ${special} too much? Let's put it next to the alternatives`,
    preview: "A clear reframe without pressure theater.",
    ctaLabel: "Review the offer calmly",
    ctaUrl: offer,
    body: [
      "Price objections deserve a straight answer.",
      `${special} is not small money. I will not insult you by pretending otherwise.`,
      "Now put it beside the alternatives. A single serious development quote can dwarf it before you even validate an idea. Months of scattered courses can cost more and still leave you without a complete path. Staying only a consumer has a quieter cost: dependence and delayed leverage.",
      "The program's stated training value is ₦450,000 because of the breadth of modules and bonuses, including templates, idea support, private support, monetization guidance, toolkit direction, marketplace thinking, lifetime access with updates, and acquisition guidance. Those are included to remove blockers, not to manufacture fake scarcity.",
      "You still have to do the work. No honest training removes that.",
      "If the skill is relevant to your next chapter, the question is whether entering at the special price makes sense before your personal deadline.",
      `After that deadline, the same program remains available at ${regular}.`,
    ],
  },
  {
    day: 28,
    subject: "Your special price has a real end date",
    preview: "The program stays. The ₦49,999 window does not.",
    ctaLabel: "Secure the current special price",
    ctaUrl: offer,
    body: [
      "I want this to be unmistakable.",
      `You currently qualify for ${special} on How To Build Software With AI And Get Paid For It.`,
      "That special price is tied to your personal campaign deadline. It is not a global rumor and not a fake countdown invented for pressure.",
      `After your deadline, the program remains available at ${regular}. The training does not vanish. Enrollment does not \"close forever.\" The preferential price ends.`,
      "That means waiting has a concrete financial consequence if you already know you want the complete path.",
      "This is a price-window decision, not an availability scare. The curriculum stays. The special rate does not. That distinction matters.",
      "If you are still unsure, use the remaining time to review the offer page carefully and decide based on fit, not impulse.",
      "If you are sure, there is no strategic benefit to paying more later for the same curriculum.",
      "Your window is personal. Treat the date as real.",
    ],
  },
  {
    day: 29,
    subject: "Why are you still hesitating?",
    preview: "A direct letter for the almost-decided.",
    ctaLabel: "Make the decision with clear eyes",
    ctaUrl: offer,
    body: [
      "By now you have heard the argument from several angles.",
      "Ownership versus consumption. Client work versus product work. Fear of not being technical. Fear of breaking things. Fear of no ideas. Fear of no time. Fear of price.",
      "So what is left?",
      "Sometimes it is perfectionism. Sometimes it is distrust of online education. Sometimes it is the comfort of postponement. Sometimes it is the quiet worry that you will buy and not execute.",
      "Only you can answer that. What I can tell you is this: the program is designed for people who will implement, not for people hunting miracles. If you will not do the work, do not buy it. If you will, delaying mainly changes the price you pay to start.",
      "Your personal special-price window is nearly closed. The program remains available afterward. The preferential rate does not.",
      "Look at the offer again and decide like an adult making a business decision, not like someone waiting for fear to disappear.",
    ],
  },
  {
    day: 30,
    subject: "Final day of your ₦49,999 window",
    preview: "Program stays open. Your special price ends at your personal Lagos deadline.",
    ctaLabel: "Join before your price returns to ₦100,000",
    ctaUrl: offer,
    body: [
      "This is the final day of your personal special-price window.",
      `Until your deadline tonight, you can still enter How To Build Software With AI And Get Paid For It at ${special}.`,
      `After that exact personal deadline, the program remains available at ${regular}. Nothing about the curriculum disappears. What ends is the preferential price assigned to your enrollment window.`,
      "If you want the complete path — setup, AI direction, blueprints, prompting method, design, functionality, data, safety, deployment, app-store readiness, plus the bonuses that remove common blockers — today is the last day to enter at the current special rate.",
      "If this is not for you, let the window close and move on without guilt. That is a clean decision too.",
      "If it is for you, paying more tomorrow for the same training is a strange form of caution.",
      "Make the decision before your personal deadline hits.",
      "The training stays. The ₦49,999 price does not.",
    ],
  },
];
