import {
  OFFER_URL,
  REGULAR_PRICE_NGN,
  SPECIAL_PRICE_NGN,
  WEBINAR_URL,
  type CampaignEmailTemplate,
} from "./types";

const webinar = WEBINAR_URL;
const offer = OFFER_URL;
const special = `₦${SPECIAL_PRICE_NGN.toLocaleString()}`;
const regular = `₦${REGULAR_PRICE_NGN.toLocaleString()}`;

export const AI_MONEY_CODE_EMAIL_TEMPLATES: CampaignEmailTemplate[] = [
  {
    day: 1,
    subject: "Repeated problems are trying to tell you something",
    preview: "The same frustration showing up every week may be a software clue.",
    ctaLabel: "Watch the free training",
    ctaUrl: webinar,
    body: [
      "If you have ever complained about the same work problem more than three times, keep reading.",
      "A repeated problem is more useful than a random burst of inspiration because repetition tells you the pain is not accidental.",
      "Think about a school owner reconciling fees by hand, an agency copying reports between tools, or a shop following up customers from memory. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Write down three tasks people around you repeat, who does each task, and what the repetition costs them. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "If this way of seeing problems is useful, watch the free training next. It shows how to turn those repeated frustrations into something buildable.",
    ],
  },
  {
    day: 2,
    subject: "Complainers and opportunity-spotters hear the same words",
    preview: "One person joins the complaint; another asks what process could remove it.",
    ctaLabel: "See how opportunity-spotting works",
    ctaUrl: webinar,
    body: [
      "Two people can watch the same broken process and walk away with opposite conclusions.",
      "One person says the system is broken and moves on. Another person asks who would pay for a cleaner version of that system.",
      "When someone says, “We always lose these records,” the useful response is not agreement alone; it is curiosity about where the records should live and who needs them. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: For one day, capture complaints without pitching. Ask what happened, how often it happens, and what they do now. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "In the free training, I show how opportunity-spotting becomes a practical process, not a personality trait.",
    ],
  },
  {
    day: 3,
    subject: "An idea is not yet a market problem",
    preview: "Good ideas become stronger when tied to a specific person and an expensive frustration.",
    ctaLabel: "Learn to test market problems",
    ctaUrl: webinar,
    body: [
      "Having an idea feels productive. It is not the same thing as finding a market problem.",
      "An idea is a thought. A market problem is a recurring pain attached to people who already spend time or money dealing with it.",
      "“An app for vendors” is foggy. “A simple order tracker for home bakers who lose paid orders inside WhatsApp” gives you someone to interview and a workflow to inspect. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Rewrite one idea as a sentence naming the user, repeated pain, current workaround, and result they want. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "Watch the free webinar if you want the method for separating exciting ideas from problems people may actually pay to solve.",
    ],
  },
  {
    day: 4,
    subject: "Technical skill is only one part of getting paid",
    preview: "A clean build with no buyer, offer, or distribution plan is still a hobby project.",
    ctaLabel: "Watch the commercial build path",
    ctaUrl: webinar,
    body: [
      "Being able to build something does not automatically mean you can sell it.",
      "Code can create a working prototype. Customers, distribution, and a clear offer create a chance at revenue.",
      "A builder can spend months polishing features while a less sophisticated competitor talks to customers, explains the value clearly, and wins the work. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Ask how a buyer would discover your tool, understand it, trust it, pay for it, and get a result. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "The free training covers both the build path and the commercial path, because one without the other leaves you stuck.",
    ],
  },
  {
    day: 5,
    subject: "AI lowered the build barrier, not the business standard",
    preview: "Access to powerful tools changed. The questions about demand and value did not.",
    ctaLabel: "See what AI changed — and what it did not",
    ctaUrl: webinar,
    body: [
      "AI made it easier to start building. It did not make the business questions disappear.",
      "You can now start earlier and cheaper than before. You still have to choose the right problem and prove someone cares.",
      "It cannot decide whether a clinic cares about your feature, whether your pricing fits the pain, or whether your message reaches the person with authority to buy. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Use AI for execution, but keep ownership of the problem, customer conversation, trade-offs, testing, and commercial decision. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "Come to the free training to see what changed with AI, and what still depends on your judgment.",
    ],
  },
  {
    day: 6,
    subject: "Everyday software has a business hiding behind it",
    preview: "The button you tap is only the visible edge of a value exchange.",
    ctaLabel: "Understand everyday software businesses",
    ctaUrl: webinar,
    body: [
      "Most people use software all day without asking who gets paid when the tool works.",
      "Payments, bookings, delivery tracking, reporting, and customer follow-up all sit on software somebody owns.",
      "A booking page looks simple, but behind it sit missed-call reduction, schedule visibility, reminders, customer records, and a reason for the business to pay. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Choose one tool you use today and map the user, the pain, the key workflow, the payer, and the reason they stay. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "If you want to see how ordinary software businesses are structured, start with the free training.",
    ],
  },
  {
    day: 7,
    subject: "Not every annoying problem deserves software",
    preview: "Use these filters before spending a week building the wrong thing.",
    ctaLabel: "Learn how to investigate problems",
    ctaUrl: webinar,
    body: [
      "Not every frustration deserves a product. Some deserve a notepad and a better question.",
      "The useful filter is simple: how often does it hurt, who feels it, and what do they do today instead?",
      "Someone mildly disliking a colour picker is different from a distributor losing orders because stock records are late and unreliable. Both are complaints; only one may carry a budget. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Score one problem for frequency, financial or emotional cost, urgency, reachability, and evidence that people seek a solution. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "The webinar walks through a practical way to investigate problems before you waste months building the wrong thing.",
    ],
  },
  {
    day: 8,
    subject: "Many software ideas fail before the first line is built",
    preview: "Bad assumptions do not become good merely because AI helped you ship quickly.",
    ctaLabel: "Watch how ideas get pressure-tested",
    ctaUrl: webinar,
    body: [
      "Plenty of software ideas die long before anyone opens a code editor.",
      "People fall in love with features before they confirm demand, distribution, or a reason someone would switch.",
      "Friends may say your concept sounds brilliant because they like you. A buyer reveals stronger evidence by sharing records, giving time, testing a rough version, or discussing a budget. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: List your biggest assumptions and design one cheap conversation or manual test for each before asking AI to build. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "Watch the free training to learn how to pressure-test an idea before you sink weeks into it.",
    ],
  },
  {
    day: 9,
    subject: "“I have no software idea” is a belief, not a fact",
    preview: "You are surrounded by workflows; you may simply not have learned how to observe them.",
    ctaLabel: "Find where ideas actually come from",
    ctaUrl: webinar,
    body: [
      "When someone says they have no software idea, they usually mean they have no glamorous idea.",
      "Look at workarounds, complaints, manual spreadsheets, and WhatsApp chaos. Those are idea mines.",
      "Your job, industry, church, neighbourhood, customers, and family businesses contain processes outsiders would never notice. Familiarity makes those processes invisible, not worthless. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Walk through one normal workday and mark every handoff, copy-and-paste step, wait, reminder, and reconciliation. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "If you think you have no idea, the free training will show you where to look first.",
    ],
  },
  {
    day: 10,
    subject: "Boring problems often have serious budgets",
    preview: "Excitement attracts attention; costly routine attracts payment.",
    ctaLabel: "See why boring problems pay",
    ctaUrl: webinar,
    body: [
      "The problems that look boring on paper are often the ones people already pay to escape.",
      "Fee tracking, inventory blind spots, appointment no-shows, and lead follow-up rarely trend on social media. They still cost businesses money every week.",
      "A business owner does not need your product to sound impressive at dinner. They need fewer errors, faster cash, better visibility, or less dependence on fragile manual work. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Look for a boring process linked directly to money, time, risk, or customer trust, then ask who owns its outcome. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "Join the free webinar and I will show you how boring operational pain becomes a buildable opportunity.",
    ],
  },
  {
    day: 11,
    subject: "Customers do not appear when the code is finished",
    preview: "Distribution deserves a place in the blueprint, not a prayer at launch.",
    ctaLabel: "Learn why customers come first",
    ctaUrl: webinar,
    body: [
      "A finished product with no customers is still unfinished work.",
      "If nobody knows the product exists, or nobody trusts it enough to try, the build was only rehearsal.",
      "Client builders may begin with direct outreach and referrals. Product builders may use partnerships, communities, content, existing audiences, or sales conversations. The channel should fit the buyer. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Before building, name your first ten reachable prospects and the honest reason each might give you twenty minutes. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "The free training includes how to think about customers, not only how to assemble features.",
    ],
  },
  {
    day: 12,
    subject: "How software money works without fantasy maths",
    preview: "There are realistic paths: paid projects, subscriptions, setup fees, support, and licences.",
    ctaLabel: "See realistic monetization paths",
    ctaUrl: webinar,
    body: [
      "People talk about software money as if there is one path. There are several, and they behave differently.",
      "Client projects, retainers, product subscriptions, and marketplace offers all monetize differently and fail differently.",
      "Each model has trade-offs. Client work can bring earlier cash but depends on delivery. Product revenue can repeat but demands validation, support, retention, and distribution. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Choose the model that matches your current resources, access to customers, appetite for support, and need for near-term cash. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "Watch the webinar for a grounded view of monetization before you invent a pricing fantasy.",
    ],
  },
  {
    day: 13,
    subject: "A product is not automatically a business",
    preview: "The software is the delivery engine; the business includes demand, sales, service, and economics.",
    ctaLabel: "Bridge product thinking to business thinking",
    ctaUrl: webinar,
    body: [
      "You can finish a product and still not have a business.",
      "A product is the tool. A business is the system that finds users, delivers value, collects payment, and improves over time.",
      "Builders often obsess over what the product can do and neglect why a buyer chooses it, how onboarding works, what support costs, and whether the numbers make sense. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Draw the full loop: discover, trust, buy, onboard, use, receive value, get support, renew, and refer. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "If you want the bridge from product thinking to business thinking, the free training is the next step.",
    ],
  },
  {
    day: 14,
    subject: "Tomorrow I will show you the bridge from problem to product",
    preview: "You have studied the opportunity; now see the practical path in one free training.",
    ctaLabel: "Watch the free webinar",
    ctaUrl: webinar,
    body: [
      "Over the last two weeks I have been building one argument with you, piece by piece.",
      "You have seen opportunity, validation, building, customers, and monetization as separate pieces. The missing piece is a process that holds them together.",
      "The free training joins those pieces with the build process: shaping a useful first version, directing AI, dealing with errors, publishing the work, and choosing a client or ownership path. The details differ across industries, but the pattern is the same: somebody has a job to complete and the current method creates avoidable friction.",
      "The weak response is to rush into features. The stronger response is to investigate. Who feels the pain most? How often does it happen? What does failure cost? Who controls a budget? What workaround have they accepted, and why has that workaround survived? Those questions protect you from building around guesses.",
      "AI matters because it can shorten the distance between a clear description and a testable piece of software. It can help draft screens, logic, copy, data structures, and fixes. But speed only multiplies your direction. If the problem is vague, faster building simply gets you to a polished wrong answer sooner.",
      "This is where business judgment enters. A customer pays for a result they understand, not for the number of prompts you typed. They may care about fewer missed follow-ups, faster reports, cleaner records, easier bookings, or better visibility. Your language should stay close to that outcome.",
      "A practical exercise for today: Set aside focused time, bring one problem from your notes, and watch How To Build Software With AI And Get Paid For It. Do not worry about naming an app or choosing technology yet. Collect evidence first and notice the words people use when they describe the frustration.",
      "The free training is called How To Build Software With AI And Get Paid For It. I show how to move from problem to blueprint, use AI through the build, recover when something breaks, publish the work, and choose between earning from clients or owning a focused product.",
      "I also explain the limits. AI does not remove the need to test, talk to customers, make decisions, or learn from errors. It gives a determined operator more execution capacity. That is useful, but only when paired with a problem worth solving and a route to people who care.",
      "You do not need to buy anything to benefit from the class. Watch it as a business lesson. Bring one real process from your notes and compare it with the framework. Even if you decide not to pursue software now, you will judge digital opportunities with better questions.",
      "Watch How To Build Software With AI And Get Paid For It. It is the cleanest way to connect everything we have covered so far.",
    ],
  },
  {
    day: 15,
    subject: "The free lessons were the map; this is the guided route",
    preview: "AI Money Code is available now for builders ready to move from understanding to execution.",
    ctaLabel: "See how AI Money Code works",
    ctaUrl: offer,
    body: [
      "There is a point where more free lessons stop helping and a structured path becomes the real next step.",
      "You now understand why software opportunities begin with problems, not prompts, and why building is only one part of creating commercial value.",
      "For the last fourteen days, I have concentrated on the thinking that comes before a purchase: finding repeated pain, checking demand, choosing a realistic money path, and planning distribution. The paid program is where that understanding becomes a guided build process.",
      "You are not crossing from education into blind pressure. You are deciding whether to continue alone or use a curriculum that organizes setup, blueprinting, building, debugging, deployment, and commercial action in the order a beginner can follow.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: Read the offer as a practical decision: do you want a guided sequence for building and monetizing, and will you set aside the time to use it? Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Start by reading the offer page from top to bottom. Notice which stage has stopped you before. The purpose of the program and its supporting resources is to remove those specific execution gaps while keeping you responsible for doing the work.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "That is the transition I want you to notice today. Free education can help you see the road, but it cannot walk beside you while you choose a project, turn it into a plan, meet the first confusing result, and decide what to fix next. The ₦49,999 offer is for that guided movement from knowing to doing; ₦100,000 is the regular price after your personal window. Do not buy merely because the conversation has changed from lessons to an offer. Buy only if having the stages arranged, explained, and supported will materially improve your chance of completing the work you already want to do.",
      "If you are ready for a guided path instead of more scattered notes, review AI Money Code on the offer page.",
    ],
  },
  {
    day: 16,
    subject: "What AI Money Code helps you do from start to ship",
    preview: "This is a working path through setup, blueprint, build, debugging, deployment, and getting paid.",
    ctaLabel: "Explore what the program helps you do",
    ctaUrl: offer,
    body: [
      "If I only told you AI Money Code exists, that would be marketing. Let me tell you what it is actually designed to help you do.",
      "AI Money Code is a structured implementation path from problem selection through blueprint, building with AI direction, usability, data, recovery, deployment, and monetization.",
      "The route begins with setup and clear AI direction, then moves into the Idea-To-Blueprint System. That order matters: a stable environment and a defined product prevent beginners from spending days fixing confusion they accidentally created at the start.",
      "The build then develops through structured prompting, interface design, functionality, data, debugging, deployment, and app-store preparation where appropriate. Each stage answers a practical question, from what to build next to how another person can access and use it.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: The aim is not tool collecting. It is moving through a complete project with enough structure to know what to do next. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Commercial guides and support sit around that core route. They help you consider ideas, clients, marketplaces, customer acquisition, and pricing without pretending that marketing can rescue a product nobody needs.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "Picture the program as a workbench, not a library shelf. You arrive with a problem worth examining, use the blueprint stage to define what the first version must do, direct AI through manageable pieces, and test each important behaviour before moving forward. When something fails, you learn how to describe the failure and work toward a correction. When the build works, deployment makes it available outside your own screen, and the commercial material helps you think about who should see it and why they might care. The value is in completing that connected cycle, because isolated lessons rarely reveal where your actual execution gap sits.",
      "See the full program outline and decide whether this is the process you have been missing.",
    ],
  },
  {
    day: 17,
    subject: "Who should join AI Money Code—and who should not",
    preview: "The right fit matters more than forcing every reader into the program.",
    ctaLabel: "Check if this is the right fit",
    ctaUrl: offer,
    body: [
      "I would rather lose a sale than enroll someone who should not buy this.",
      "This program is for people willing to investigate problems, follow a process, and do the work. It is not for people hunting guaranteed money.",
      "A good-fit student does not need to know syntax, but must be able to describe a problem, follow a sequence, test what the software does, and return to a lesson when a result is wrong. Curiosity and follow-through matter more than performing technical confidence.",
      "A poor-fit buyer wants a certificate without a project, refuses to show work to users, or expects private support to replace personal effort. The curriculum can organize your work; it cannot create discipline on your behalf.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: If you can protect regular learning time and accept that debugging and feedback belong to the process, you have the posture the curriculum expects. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Lifetime access and free updates reduce the need to rush, but they should not become permission to postpone. A sensible student chooses a problem early and uses each module to move that same project forward.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "There is another fit test people overlook: how you respond when the first answer is not clean. A suitable student can pause, compare the result with the brief, ask a better question, and try again without treating correction as failure. You may be a marketer, consultant, business owner, employee, freelancer, or complete beginner; the label matters less than your willingness to observe carefully and finish small commitments. On the other hand, if you dislike customer conversations, will not test your assumptions, or need every step done on your behalf, the program will frustrate you. Honest exclusion protects your money and protects the standard of the work.",
      "If the fit is clear, explore the offer. If it is not, save your money.",
    ],
  },
  {
    day: 18,
    subject: "The software business opportunity is wider than launching an app",
    preview: "Client solutions, internal tools, focused products, and licences can all create value.",
    ctaLabel: "Review the ownership path",
    ctaUrl: offer,
    body: [
      "Look at how many businesses you touch in a normal week that depend on software to operate.",
      "Software ownership creates leverage when the product solves a real job. That is the opportunity, not celebrity comparison.",
      "The program does not force every student toward the same business model. The Get-Paid Guide supports the client route, while the Software Marketplace Guide helps you think about products and places where software demand already exists.",
      "Client work can teach discovery, scoping, delivery, and communication while producing earlier revenue. Ownership can create repeatable value, but adds customer acquisition, retention, support, and product decisions. You can begin with one path and learn into the other.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: The Software Marketplace Guide and Idea Vault help you consider demand and opportunity while the main curriculum builds your execution ability. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "The Idea Vault is useful only when paired with investigation. Treat its options as prompts for market conversations, not ready-made promises that buyers are waiting. Your chosen opportunity still needs evidence.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "One useful way to see the opportunity is to stop asking, “What big app can I launch?” and ask, “Whose valuable work can I make easier?” A logistics operator may need clearer delivery visibility. A consultant may need a client intake system. A school may need a better way to reconcile records. Each can begin as a focused solution for one buyer before it ever becomes a wider product. That range matters because you do not need to imitate a famous technology company. You need enough market access to learn the workflow, enough building ability to improve it, and a sensible way to exchange that improvement for value.",
      "If ownership and leverage are the kind of opportunity you want to pursue seriously, review the program.",
    ],
  },
  {
    day: 19,
    subject: "Spectating has a cost even when no invoice arrives",
    preview: "Watching AI demos feels productive until another month ends with nothing shipped.",
    ctaLabel: "See the structured next step",
    ctaUrl: offer,
    body: [
      "Staying on the sidelines does not feel expensive day by day. The cost shows up later.",
      "Another year of consuming tools without learning to create them has a quiet price: delayed skill and delayed options.",
      "Spectators often know the names of every new AI tool while remaining unable to define one customer workflow from beginning to end. Builders choose a narrow job, tolerate an imperfect first attempt, and learn from something real.",
      "Zero-To-Builder Setup gives you a concrete starting line. Its value is not the information alone; it is ending the cycle of changing tools, rearranging plans, and calling preparation progress.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: Choose a problem and a build schedule. If you join, use the Zero-To-Builder Setup immediately and create momentum while the decision is fresh. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Private support can help when you have attempted the work and can explain where you are stuck. It is most useful as a safety rail for action, not a place to outsource the whole build.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "The hidden cost is not that everybody who starts today will immediately earn while you do not. That would be dishonest. The real cost is that practice compounds. A person who completes one small build learns what a useful brief looks like, where AI misunderstands them, how users react, and which commercial questions they avoided. Their second attempt starts from experience. A spectator starts each new month from another collection of saved videos. Even an imperfect project can produce reusable judgment, contacts, and clarity. If this capability matters to your future, measure delay in missed learning cycles, not only in naira paid at checkout.",
      "If you are tired of watching from the outside, look at the structured path now while your special price still applies.",
    ],
  },
  {
    day: 20,
    subject: "You do not need to become a traditional programmer first",
    preview: "You need problem clarity, patient direction, testing habits, and a willingness to learn.",
    ctaLabel: "See how non-technical builders start",
    ctaUrl: offer,
    body: [
      "If your main hesitation is that you are not technical, that hesitation deserves a direct answer.",
      "You do not need to become a traditional engineer first. You do need judgment, clear instructions, and the patience to inspect what AI produces.",
      "Teaching AI To Build For You focuses on giving context, setting constraints, breaking work into steps, and checking the result. Those are management skills expressed through software, and capable non-technical operators already use versions of them in ordinary business.",
      "The Prompt Playbook supports repeatable instructions instead of random requests. Your Safety Net focuses on errors and recovery, because a non-technical builder needs a dependable way to investigate failure rather than pretending bugs will not happen.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: Teaching AI To Build For You, the Prompt Playbook, and Your Safety Net are designed around that operator role rather than pretending one sentence creates a finished business. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "You will learn technical ideas along the way, but the immediate goal is not to win a vocabulary contest. It is to make sound decisions and guide a useful project to completion.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "Think of your role as the person responsible for clarity. You tell the system what the user is trying to achieve, what information must be collected, what should happen after a button is pressed, and what a correct result looks like. AI can help translate that direction into a working interface and logic, but you remain the person checking whether the outcome makes sense. This is closer to supervising a capable but literal assistant than sitting an engineering examination. The habit you are building is structured communication: small instructions, visible tests, recorded errors, and deliberate corrections. That habit is learnable without pretending the technical parts do not exist.",
      "If technical intimidation has been your wall, read the offer with that objection in mind and judge the method honestly.",
    ],
  },
  {
    day: 21,
    subject: "No idea? Start with evidence, not inspiration",
    preview: "The Idea-To-Blueprint System gives your observation a disciplined next step.",
    ctaLabel: "Explore the idea-finding process",
    ctaUrl: offer,
    body: [
      "Blank-page panic has stopped more capable people than lack of tools ever did.",
      "Start from observed friction in real work. Then shape the smallest useful version of a fix.",
      "The Idea Vault can help when your observation muscle is still developing, but the Idea-To-Blueprint System does the more important work: narrowing a possibility into a specific user, job, flow, information need, and testable first version.",
      "A blueprint stops the idea from expanding every time you see another feature online. It gives AI a clearer brief and gives you a basis for deciding whether a proposed screen or function belongs in the first build.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: Start with a problem interview this week. A blueprint grounded in evidence is worth more than fifty exciting concepts with no named buyer. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "You can enter without a grand concept. Bring access to a real environment and a willingness to ask people how work gets done. Evidence gathered during the program can shape the idea.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "Here is a simple place to begin: ask one business owner to show you a task they repeat every week. Watch the task from the first trigger to the final result. Note every handoff, delay, duplicate entry, forgotten reminder, and decision that depends on missing information. Then describe the smallest change that would make one part easier. That observation is already more valuable than forcing yourself to invent a clever app name. Inside the program, the idea process gives those notes a shape AI can work with. You are not expected to arrive with genius; you are expected to arrive willing to look closely.",
      "If idea-finding has blocked you, the program is built to start from evidence. See what is included.",
    ],
  },
  {
    day: 22,
    subject: "“What if nobody wants it?” is the right fear to investigate",
    preview: "Validation turns a frightening guess into evidence you can use before overbuilding.",
    ctaLabel: "See how validation is taught",
    ctaUrl: offer,
    body: [
      "Worrying that nobody will want what you build is not weakness. It is a useful warning.",
      "Validation exists to protect your time. Checking demand before heavy building is part of the method, not an optional extra.",
      "Validation belongs before and during the build. The Idea-To-Blueprint work helps expose assumptions, while a narrow first version lets you test behaviour instead of collecting polite opinions about a large concept.",
      "Customer acquisition guidance is relevant here because validation requires access. You need a practical way to find and speak with the people named in your blueprint, not a generic audience that cannot confirm the pain.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: Use the blueprint as a hypothesis. Build the smallest version needed to test the most dangerous assumption, then let evidence guide the next feature. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "If evidence weakens an idea, that is useful progress. A smaller correction before a long build is cheaper than defending a product simply because you spent time making it.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "Good validation is not asking friends whether an idea sounds nice. Ask a potential user to walk through the current process, show where time or money leaks, explain what they have tried, and identify what would make a new method trustworthy. Stronger signals include agreeing to test a rough workflow, introducing you to the decision-maker, sharing representative data safely, or discussing what a useful solution could be worth. None of those signals guarantees a sale, but they improve the quality of your next decision. The goal is not to prove yourself right. It is to discover what must be true before you spend heavily on the build.",
      "If validation fear is your real concern, review how the program handles demand before heavy build work.",
    ],
  },
  {
    day: 23,
    subject: "The proof I can share—and the promise I will not make",
    preview: "Real outcomes show commercial possibility; they do not predict your personal result.",
    ctaLabel: "Review the proof and the offer",
    ctaUrl: offer,
    body: [
      "I will only use proof I can stand behind. That means fewer stories, and clearer ones.",
      "LeadThur’s early traction, client delivery results I have shared, and careful operator context are useful. They are not a script for your bank account.",
      "LeadThur is the closest product example in this conversation because you already use it. Its numbers matter as evidence that a focused problem and working distribution can create value, not as a formula every new tool will repeat.",
      "The client examples show another route: businesses can pay meaningful fees for delivery when the work solves a clear problem. The Get-Paid Guide adds practical commercial framing, but no guide can promise the size or timing of a future project.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: PromptEarn has processed ₦800M+ and given out 20+ cars. That is operator credibility, not proof that this AI curriculum created PromptEarn or that students will reproduce those numbers. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Keep PromptEarn in the correct category. Its record supports my operator credibility and experience building businesses; it is not evidence that this curriculum produced PromptEarn, and I will not use it to imply that.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "When you examine proof, separate three questions. First, has the person teaching demonstrated that they can build and operate real products? Second, does the curriculum contain a credible process you can inspect? Third, are you personally prepared to apply that process in your own market? Evidence for the first two can support a buying decision, but it cannot answer the third for you. Your network, chosen problem, consistency, offer, and timing will shape your outcome. I prefer that distinction because durable confidence comes from knowing what the evidence actually supports. Exciting numbers without context may attract attention, but they are a poor foundation for responsible action.",
      "Judge the proof for yourself on the offer page, then decide with clear eyes.",
    ],
  },
  {
    day: 24,
    subject: "Is ₦49,999 too much for this program?",
    preview: "Put the price beside the complete path, the alternatives, and the work you intend to do.",
    ctaLabel: "Weigh the ₦49,999 decision",
    ctaUrl: offer,
    body: [
      "₦49,999 is real money. Pretending otherwise would insult both of us.",
      "The question is whether the skill and process are worth that investment to you before the special price becomes the regular price.",
      "The price covers a connected path rather than one isolated tool tutorial. Setup, blueprinting, AI direction, usable design, functionality, data, debugging, deployment, and monetization are taught as parts of the same job: shipping something useful.",
      "Lifetime access and free updates matter if your schedule requires a steady pace or tools change after you join. Private support matters if it helps you resolve a real sticking point. Neither has value when lessons remain unopened.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: The value depends on use. Lifetime access, free updates, guides, the Prompt Playbook, Idea Vault, templates, support, and acquisition guidance matter only if you implement. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Measure the purchase against a project you genuinely want to pursue. If there is no problem you are willing to investigate and no time you will protect, even a lower price would be expensive.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "To weigh ₦49,999 properly, compare complete alternatives rather than comparing the course with doing nothing. Piecing the path together may cost less cash, but it can cost search time, contradictory advice, and abandoned starts. Hiring somebody may move faster, but you still need enough understanding to scope and judge the work. Joining gives you an organized route, yet it only becomes cheaper in practice when you use it. The regular ₦100,000 price makes the current difference clear, but price alone should not make the decision. Base it on the project you intend to pursue, the hours you can protect, and the specific gaps the curriculum addresses.",
      "If the investment feels heavy, compare it against what you are trying to learn, then decide before the special price becomes ₦100,000.",
    ],
  },
  {
    day: 25,
    subject: "What happens after you buy AI Money Code",
    preview: "A clear first-week plan is more useful than purchase excitement.",
    ctaLabel: "See what happens after you join",
    ctaUrl: offer,
    body: [
      "Before you decide, you should know what the first weeks inside the program actually look like.",
      "You get immediate access, start with setup, then move through blueprints, prompting method, building, safety, deployment, and monetization guidance.",
      "Do not begin by opening every bonus. Begin with setup and one candidate problem. Complete the early lessons in sequence, write down your assumptions, and choose a small output for the week.",
      "When your blueprint is clear, use the Prompt Playbook in context on that project. Save the instructions and results that work. A personal operating record is more useful than a folder of impressive prompts copied without understanding.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: Your first target should be a validated problem and a narrow blueprint, followed by a working milestone you can test. Progress becomes easier to manage when each stage has a visible output. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Use support after making a specific attempt. Share what you expected, what happened, and what you already tried. That habit improves the help you receive and teaches the debugging discipline you will need after the course.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "A sensible first week is quiet and practical. Set up your tools, choose one real problem, reserve two or three focused work blocks, and produce a written blueprint you can explain to another person. In the following stage, build one visible workflow rather than attempting the entire dream at once. Keep a short project log: what you asked AI to do, what it produced, what failed, and what you changed. That record stops you from repeating mistakes and makes support conversations useful. Purchase excitement is temporary; a calendar, a narrow milestone, and evidence of weekly progress are what turn access into a finished capability.",
      "If the post-purchase path sounds like something you will actually follow, secure your place at the current special price.",
    ],
  },
  {
    day: 26,
    subject: "The real decision is not “course or no course”",
    preview: "It is whether you will build this capability with structure now, piece it together, or postpone it.",
    ctaLabel: "Make your decision on the offer page",
    ctaUrl: offer,
    body: [
      "By now the choice is simpler than it looks.",
      "Either keep collecting fragments and delaying action, or follow a structured path and decide if this opportunity deserves serious effort.",
      "If you choose self-study, define the sources, project, weekly hours, and shipping date. If you choose to hire, define the budget and how you will validate before committing. A real alternative deserves more detail than saying you will figure it out someday.",
      "AI Money Code offers sequence, supporting guides, updates, and help in one place. The advantage is reduced fragmentation. The trade is that you still pay with attention and practice after paying the fee.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: If you join, commit to execution. If you decline, choose a concrete alternative with dates and outputs so “later” does not quietly become another year. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "The most important question is whether software-building capability supports your business direction. When the answer is weak, wait. When the answer is strong, choose a learning route and begin deliberately.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "Make the comparison on paper. Route one is structured learning: the fee, scheduled practice, one project, and a sequence to follow. Route two is independent learning: named resources, a realistic research budget, milestones, and a person or community you can turn to when blocked. Route three is postponement: no immediate expense, but also no defined date for developing the capability. Once the routes are concrete, the decision becomes less emotional. I am not asking you to claim AI Money Code is the only route. I am asking you to stop treating an undefined intention as if it were an equally reliable plan. Choose the route you will genuinely execute.",
      "Make the decision. Review the offer and choose the path that matches how seriously you want to work.",
    ],
  },
  {
    day: 27,
    subject: "Waiting has a price that does not show on checkout",
    preview: "Delay can cost skill, feedback, customer knowledge, and eventually a higher entry price.",
    ctaLabel: "Secure the special price while it lasts",
    ctaUrl: offer,
    body: [
      "Delay does not freeze the price. That is the part many people ignore.",
      "Your personal special price is time-bound. After it ends, AI Money Code remains available at the regular rate.",
      "Tool access will continue changing, which makes a fixed collection of tricks less valuable than a repeatable process for defining, building, testing, and shipping. Process improves through use, not observation.",
      "Lifetime access means you can revisit material, and free updates help the training evolve. Those features reduce content pressure, but they cannot return the customer conversations or practice you postpone.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: Your personal special rate also has a defined window. Separate the emotional wish for certainty from the evidence you already have, then decide. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Waiting for perfect certainty is especially costly in product work because evidence comes from action. A small interview or rough test teaches more than another month of private speculation.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "The price decision is specific: enter during your personal window at ₦49,999, or pay the regular ₦100,000 if you choose to join afterward. The learning decision is broader. Every week you wait is a week without a completed blueprint, a customer interview, a tested workflow, or a clearer understanding of where you struggle. That does not mean you should rush into a poor fit. It means “I will decide later” should have a date and a reason. If your questions have been answered and the work fits your direction, delay is no longer research. It is simply postponing both the lower price and the first learning cycle.",
      "If you already know you want the complete path, waiting mainly changes what you pay.",
    ],
  },
  {
    day: 28,
    subject: "Everything AI Money Code includes, in one clear picture",
    preview: "A focused recap of the build path, commercial path, and support around both.",
    ctaLabel: "Review the full program",
    ctaUrl: offer,
    body: [
      "Let me put the whole offer in one place so you can judge it cleanly.",
      "Problem, opportunity, fit, process, objections, price, and your personal deadline all belong in one clear decision.",
      "The core route is sequential: prepare your environment, direct AI, turn a problem into a blueprint, prompt with structure, improve the interface, add functionality and data, debug failures, deploy publicly, and consider app stores where they fit.",
      "The commercial layer includes idea support, client and marketplace guidance, customer acquisition thinking, and templates that help you move from a build toward an offer. It supports action around the product rather than treating code as the whole business.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: Those pieces serve one job: helping a committed beginner move from a vague interest in AI software to a useful project and a realistic route to customers. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Private support, toolkit direction, lifetime access, and free updates help you continue when circumstances or tools change. This recap is broad because today’s job is to inspect the whole system before deciding.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "Here is the recap in terms of outputs. You should be able to move from a researched problem to a written blueprint; from that blueprint to clear instructions AI can follow; from an early build to tested functionality, usable data, and a public version; and from a public version to conversations about clients, customers, or a focused product. Around that route sit debugging help, prompts, ideas, templates, updates, and support. No single bonus is the reason to join. The reason would be that this complete chain matches a capability you want to build and gives you a more orderly way to practise it than the path you have now.",
      "This is the full picture. Review it once carefully, then decide.",
    ],
  },
  {
    day: 29,
    subject: "Your special-price deadline is approaching",
    preview: "The program stays available; the difference is whether you enter at ₦49,999 or ₦100,000.",
    ctaLabel: "Choose before your price window closes",
    ctaUrl: offer,
    body: [
      "Your personal special-price window is getting short.",
      "The preferential rate is ending. The program itself does not disappear.",
      "At this stage, reopening every lesson title will not make the decision clearer. Return to your largest concern: fit, time, price, technical fear, idea quality, or market uncertainty. The earlier emails gave you a framework for each.",
      "If a factual question about the curriculum remains, verify it on the offer page. If the concern is whether you will execute, look at your calendar and choose the hours now. That answer comes from you, not another feature list.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: The deadline is about your price, not the disappearance of the training. That makes the choice simpler and more accurate. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Your special price rewards deciding within the personal window. The program’s continued availability means you can still join later, but doing so at the regular price will not add anything to the curriculum.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "For clarity, the financial choice in front of you is ₦49,999 within your current window versus ₦100,000 after it closes. There is no hidden claim that the knowledge becomes unavailable tomorrow. What disappears is this price for you. Before acting, check three things once: the curriculum answers the gap you actually have, the payment fits your finances, and your calendar contains time to implement. If all three are yes, another round of hesitation adds no useful information. If one is no, name it honestly. A deadline should bring an already-informed decision to a close; it should never replace the thinking required to make that decision.",
      "Your special-price window is closing. If you are joining, do it while the rate still applies.",
    ],
  },
  {
    day: 30,
    subject: "Final day: your ₦49,999 price ends today",
    preview: "AI Money Code remains available afterward at ₦100,000, but your personal special rate ends.",
    ctaLabel: "Get AI Money Code at ₦49,999 today",
    ctaUrl: offer,
    body: [
      "This is the last day of your ₦49,999 rate for AI Money Code.",
      "You have the full case. Today decides whether you enter at the special rate or later at the regular rate.",
      "There is no need for another curriculum tour today. You have seen the problem-first approach, the build sequence, the customer and money paths, the supported proof, and the limits of what training can do for you.",
      "Enrollment gives you immediate access, so you can begin with setup and your first problem after joining. Lifetime access and updates remain part of the program; today’s deadline changes the price, not those learning terms.",
      "Commercial guidance sits alongside the build. Depending on your goal, you can explore paid client projects, focused software products, setup and support work, or other realistic arrangements. You still have to validate demand, speak to customers, make an offer, deliver, and improve. The program does not perform those responsibilities for you.",
      "Your practical next step is simple: If the fit is wrong or you will not make time to implement, do not buy from pressure. If the fit is right and you are ready to work, complete your enrollment today. Then ask whether structured guidance would help you carry that work through to a shipped result instead of another abandoned idea.",
      "Use the offer page to complete the decision. If you join, put your first study block on the calendar before the purchase excitement fades and start with the sequence rather than browsing at random.",
      "Please judge fit honestly. You do not need a programming background, but you do need patience, regular practice, willingness to test, and enough humility to correct weak assumptions. If you want effortless cash or perfect output from one prompt, this is not the right purchase.",
      "AI Money Code is available now at ₦49,999. Your personal special-price window ends separately from program availability. After that window, the same program remains available at ₦100,000. I am stating both prices so you can make a clean financial decision without a false claim that the training disappears.",
      "So make today practical. If you are joining at ₦49,999, complete the enrollment, choose the first problem you will investigate, and put your opening study session on the calendar. Do not wait for a perfect project or spend the evening comparing ten more tools. Begin with the sequence and let the early work sharpen your direction. If you decide not to join, write down the alternative route you will follow and when it begins. Tomorrow the program will still be available at ₦100,000, but this personal rate will be finished. Either choice can be responsible; drifting past the decision without choosing a route gives you neither savings nor progress.",
      "If AI Money Code is the path you want, today is the last day to enter at ₦49,999. After that, the same program remains available at ₦100,000.",
    ],
  }
];
